services:
  web:
    build: .
    ports:
      - "92:80"
    restart: unless-stopped
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - web-network

networks:
  web-network:
    driver: bridge